Vagrant.configure('2') do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.provision :ansible do |ansible|
    ansible.playbook = 'playbook.yml'
    ansible.extra_vars = { ansible_ssh_user: 'ubuntu',  ansible_python_interpreter: '/usr/bin/python2.7', vagrant: true }

    ansible.verbose = 'v'
  end
end
